# generated by parse_bolib.jl
# nonlinear testbed of BOLIBver2
# maximum number of variables: 4

# Parsing instance AiyoshiShimizu1984Ex2 (number 1)
const NX_1 = 2
const NY_1 = 2
const nG_1 = 5
const ng_1 = 6

function F_1(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 2*x[1]+2*x[2]-3*y[1]-3*y[2]-60
end

function G_1(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x[1]+x[2]+y[1]-2*y[2]-40; x .- 50; -x]
end

function f_1(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (y[1]-x[1]+20)^2+(y[2]-x[2]+20)^2
end

function g_1(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [2*y-x .+ 10; -y .- 10; y .- 20]
end

# Parsing instance AllendeStill2013 (number 2)
const NX_2 = 2
const NY_2 = 2
const nG_2 = 5
const ng_2 = 2

function F_2(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-1)^2 + (x[2]-1)^2 .+ y'*y
end

function G_2(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x; x[1]-2; -y]
end

function f_2(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y'*y .- 2*x'*y
end

function g_2(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (y .- 1).^2-0.25
end

# Parsing instance Bard1988Ex1 (number 3)
const NX_3 = 1
const NY_3 = 1
const nG_3 = 1
const ng_3 = 4

function F_3(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-5)^2+(2*y[1]+1)^2
end

function G_3(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]
end

function f_3(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (y[1]-1)^2-1.5*x[1]*y[1]
end

function g_3(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-3*x[1]+y[1]+3; x[1]-0.5*y[1]-4; x[1]+y[1]-7; -y[1]]
end

# Parsing instance Bard1988Ex3 (number 4)
const NX_4 = 2
const NY_4 = 2
const nG_4 = 3
const ng_4 = 4

function F_4(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]^2-3*x[2]-4*y[1]+y[2]^2
end

function G_4(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x[1]^2+2*x[2]-4; -x ]
end

function f_4(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 2*x[1]^2 .+ y[1]^2-5*y[2]
end

function g_4(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]^2+2*x[1]-x[2]^2 + 2*y[1]-y[2]-3
    -x[2]-3*y[1]+4*y[2]+4; -y]
end

# Parsing instance Bard1991Ex1 (number 5)
const NX_5 = 1
const NY_5 = 2
const nG_5 = 2
const ng_5 = 3

function F_5(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]+y[2]
end

function G_5(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]+2; x[1]-4]
end

function f_5(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 2*y[1]+x[1]*y[2]
end

function g_5(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x[1]-y[1]-y[2]+4; -y]
end

# Parsing instance BardBook1998 (number 6)
const NX_6 = 2
const NY_6 = 2
const nG_6 = 4
const ng_6 = 7

function F_6(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return sum((y-x .+ 20).^2)
end

function G_6(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x .- 50; -x]
end

function f_6(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [2 2]*x-[3 3]*y .- 60
end

function g_6(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [[1 1]*x+[1 -2]*y .- 40;  2*y-x .+ 10; y .- 20; -y .- 10]
end

# Parsing instance CalamaiVicente1994a (number 7)
const NX_7 = 1
const NY_7 = 1
const nG_7 = 0
const ng_7 = 3

function F_7(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-1)^2/2+y[1]^2/2
end

function G_7(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_7(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]/2-x[1]*y[1]
end

function g_7(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x[1]-y[1]-1; -x[1]-y[1]+1; x[1]+y[1]-rho]
end

# Parsing instance ClarkWesterberg1990a (number 8)
const NX_8 = 1
const NY_8 = 1
const nG_8 = 2
const ng_8 = 3

function F_8(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-3)^2+(y[1]-2)^2
end

function G_8(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x[1]-8; -x[1]]
end

function f_8(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (y[1]-5)^2
end

function g_8(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-2*x[1]+y[1]-1; x[1]-2*y[1]+2; x[1]+2*y[1]-14]
end

# Parsing instance Colson2002BIPA1 (number 9)
const NX_9 = 1
const NY_9 = 1
const nG_9 = 3
const ng_9 = 3

function F_9(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (10-x[1])^3+(10-y[1])^3
end

function G_9(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x[1]-5; -x[1]+y[1]; -x[1]]
end

function f_9(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]+2*y[1]-15)^4
end

function g_9(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x[1]+y[1]-20; y[1]-20; -y[1]]
end

# Parsing instance Colson2002BIPA2 (number 10)
const NX_10 = 1
const NY_10 = 1
const nG_10 = 1
const ng_10 = 4

function F_10(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-5)^2+(2*y[1]+1)^2
end

function G_10(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]
end

function f_10(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (y[1]-1)^2-1.5*x[1]*y[1]+x[1]^3
end

function g_10(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-3*x[1]+y[1]+3; x[1]-0.5*y[1]-4; x[1]+y[1]-7; -y[1]]
end

# Parsing instance Colson2002BIPA3 (number 11)
const NX_11 = 1
const NY_11 = 1
const nG_11 = 2
const ng_11 = 2

function F_11(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-5)^4+(2*y[1]+1)^4
end

function G_11(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x[1]+y[1]-4; -x[1]]
end

function f_11(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return exp(-x[1]+y[1])+x[1]^2+2*x[1]*y[1]+y[1]^2+2*x[1]+6*y[1]
end

function g_11(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]+y[1]-2; -y[1]]
end

# Parsing instance Colson2002BIPA4 (number 12)
const NX_12 = 1
const NY_12 = 1
const nG_12 = 2
const ng_12 = 2

function F_12(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]^2+(y[1]-10)^2
end

function G_12(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x[1]+2*y[1]-6; -x[1]]
end

function f_12(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]^3+2*y[1]^3+x[1]-2*y[1]-x[1]^2
end

function g_12(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]+2*y[1]-3; -y[1]]
end

# Parsing instance Colson2002BIPA5 (number 13)
const NX_13 = 1
const NY_13 = 2
const nG_13 = 1
const ng_13 = 6

function F_13(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-y[2])^4+(y[1]-1)^2+(y[1]-y[2])^2
end

function G_13(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]
end

function f_13(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 2*x[1]+exp(y[1])+y[1]^2+4*y[1]+2*y[2]^2-6*y[2]
end

function g_13(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [6*x[1]+y[1]^2+exp(y[2])-15; 5*x[1]+y[1]^4 .- y[2]-25; y[1]-4; y[2]-2; -y]
end

# Parsing instance DeSilva1978 (number 14)
const NX_14 = 2
const NY_14 = 2
const nG_14 = 0
const ng_14 = 4

function F_14(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return sum((x .- 1).^2 .+ y.^2)-2
end

function G_14(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_14(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return sum((y-x).^2)
end

function g_14(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y .+ 0.5; y .- 1.5]
end

# Parsing instance Dempe1992a (number 15)
const NX_15 = 2
const NY_15 = 2
const nG_15 = 1
const ng_15 = 2

function F_15(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[2]
end

function G_15(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return sum((x+[0;1]).^2)-1
end

function f_15(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return .5*sum((y-[1;0]).^2)
end

function g_15(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [y[1]+y[2]*x[1]+x[2]; y[1]]
end

# Parsing instance Dempe1992b (number 16)
const NX_16 = 1
const NY_16 = 1
const nG_16 = 0
const ng_16 = 1

function F_16(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-3.5)^2+(y[1]+4)^2
end

function G_16(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_16(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (y[1]-3)^2
end

function g_16(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]^2-x[1]
end

# Parsing instance DempeDutta2012Ex24 (number 17)
const NX_17 = 1
const NY_17 = 1
const nG_17 = 0
const ng_17 = 1

function F_17(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-1)^2+y[1]^2
end

function G_17(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_17(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]^2*y[1]
end

function g_17(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]^2
end

# Parsing instance DempeDutta2012Ex31 (number 18)
const NX_18 = 2
const NY_18 = 2
const nG_18 = 4
const ng_18 = 2

function F_18(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -y[2]
end

function G_18(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x; y[1]*y[2]; -y[1]*y[2]]
end

function f_18(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return sum((y+[0;1]).^2)
end

function g_18(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [(y[1]-x[1])^2+(y[2]-x[1]-1)^2-1; (y[1]+x[2])^2+(y[2]-x[2]-1)^2-1]
end

# Parsing instance DempeEtal2012 (number 19)
const NX_19 = 1
const NY_19 = 1
const nG_19 = 2
const ng_19 = 2

function F_19(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]
end

function G_19(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-1-x[1];x[1]-1]
end

function f_19(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]*y[1]
end

function g_19(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1];y[1]-1]
end

# Parsing instance DempeFranke2011Ex41 (number 20)
const NX_20 = 2
const NY_20 = 2
const nG_20 = 4
const ng_20 = 4

function F_20(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]+y'*y
end

function G_20(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-1 .- x[1];-1 .+ x[1];-1 .- x[2];1 .+ x[2]]
end

function f_20(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x'*y
end

function g_20(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-2*y[1]+y[2]; y .- 2; -y[2]]
end

# Parsing instance DempeFranke2011Ex42 (number 21)
const NX_21 = 2
const NY_21 = 2
const nG_21 = 4
const ng_21 = 3

function F_21(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]+sum((y-[1;0]).^2)
end

function G_21(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-1 .- x[1];-1 .+ x[1];-1 .- x[2];1 .+ x[2]]
end

function f_21(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x'*y
end

function g_21(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]+y[2]-1; y[1]+y[2]-3.5; y[2]-2]
end

# Parsing instance DempeFranke2014Ex38 (number 22)
const NX_22 = 2
const NY_22 = 2
const nG_22 = 4
const ng_22 = 4

function F_22(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [2 1]*x+[2 -1]*y
end

function G_22(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-1 .- x[1];-1 .+ x[1];-1 .- x[2];0.75 .+ x[2]]
end

function f_22(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x'*y
end

function g_22(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-2*y[1]+y[2]; y .- 2; -y[2]]
end

# Parsing instance DempeLohse2011Ex31a (number 23)
const NX_23 = 2
const NY_23 = 2
const nG_23 = 0
const ng_23 = 4

function F_23(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return sum((x-.5).^2)-[3 3]*y
end

function G_23(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_23(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return sum(x.*y)
end

function g_23(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [sum(y)-2; -y[1]+y[2]; -y]
end

# Parsing instance FalkLiu1995 (number 24)
const NX_24 = 2
const NY_24 = 2
const nG_24 = 0
const ng_24 = 4

function F_24(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return sum((x .- 1.5).^2 .+ y.^2)-4.5
end

function G_24(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_24(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return sum((y-x).^2)
end

function g_24(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y .+ 0.5; y .- 1.5]
end

# Parsing instance FloudasEtal2013 (number 25)
const NX_25 = 2
const NY_25 = 2
const nG_25 = 4
const ng_25 = 7

function F_25(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [2 2]*x-[3 3]*y .- 60
end

function G_25(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x .- 50; -x]
end

function f_25(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return sum( (y-x .+ 20).^2 )
end

function g_25(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [2*y-x .+ 10;[1 1]*x+[1 -2]*y .- 40; -y .- 10;y .- 20]
end

# Parsing instance FloudasZlobec1998 (number 26)
const NX_26 = 1
const NY_26 = 2
const nG_26 = 2
const ng_26 = 6

function F_26(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x[1]^3 1]*y
end

function G_26(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]; x[1]-1]
end

function f_26(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -y[2]
end

function g_26(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y-[1;0]; y-[1; 100]; x[1]*y[1]-10; y[1]^2+x[1]*y[2]-1]
end

# Parsing instance GumusFloudas2001Ex1 (number 27)
const NX_27 = 1
const NY_27 = 1
const nG_27 = 3
const ng_27 = 3

function F_27(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 16*x[1]^2+9*y[1]^2
end

function G_27(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]; x[1]-12.5; -4*x[1]+y[1]]
end

function f_27(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]+y[1]-20)^4
end

function g_27(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]; y[1]-50; 4*x[1]+y[1]-50]
end

# Parsing instance GumusFloudas2001Ex4 (number 28)
const NX_28 = 1
const NY_28 = 1
const nG_28 = 5
const ng_28 = 2

function F_28(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-3)^2+(y[1]-2)^2
end

function G_28(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]; x[1]-8; -2*x[1]+y[1]-1; x[1]-2*y[1]+2; x[1]+2*y[1]-14]
end

function f_28(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (y[1]-5)^2
end

function g_28(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]; y[1]-10]
end

# Parsing instance GumusFloudas2001Ex5 (number 29)
const NX_29 = 1
const NY_29 = 2
const nG_29 = 2
const ng_29 = 6

function F_29(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]
end

function G_29(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]+0.1; x[1]-10]
end

function f_29(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -y[1]+0.5864*(y[1]^0.67)
end

function g_29(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y .+ 0.1; y .- 10; a/y[2]+0.1*y[1]-1;(4*x[1]+2*x[1]^(-0.71))/y[2]+a*x[1]^(-1.3)-1]
end

# Parsing instance HatzEtal2013 (number 30)
const NX_30 = 1
const NY_30 = 2
const nG_30 = 0
const ng_30 = 2

function F_30(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]+2*y[1]+y[2]
end

function G_30(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_30(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-y[1])^2 .+ y[2]^2
end

function g_30(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -y
end

# Parsing instance HendersonQuandt1958 (number 31)
const NX_31 = 1
const NY_31 = 1
const nG_31 = 2
const ng_31 = 1

function F_31(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (0.5*(x[1]+y[1])-95)*x[1]
end

function G_31(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [1;-1]*x[1]-[200;0]
end

function f_31(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (y[1]+0.5*x[1]-100)*y[1]
end

function g_31(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -y[1]
end

# Parsing instance HenrionSurowiec2011 (number 32)
const NX_32 = 1
const NY_32 = 1
const nG_32 = 0
const ng_32 = 0

function F_32(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]^2+c*y[1]
end

function G_32(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_32(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (y[1]/2-x[1])*y[1]
end

function g_32(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

# Parsing instance IshizukaAiyoshi1992a (number 33)
const NX_33 = 1
const NY_33 = 2
const nG_33 = 1
const ng_33 = 5

function F_33(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]*y[2]^2
end

function G_33(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]-M
end

function f_33(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]
end

function g_33(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -[1; 1; 1; 0; 0]*x[1]+[0 0; -1 0; 1 0; -1 -1; 1 1]*y-[ 0; 0; 0; M; M]
end

# Parsing instance KleniatiAdjiman2014Ex3 (number 34)
const NX_34 = 1
const NY_34 = 1
const nG_34 = 2
const ng_34 = 2

function F_34(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]-y[1]
end

function G_34(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1]
end

function f_34(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]*y[1]^2/2-x[1]*y[1]^3
end

function g_34(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance LamparielloSagratella2017Ex23 (number 35)
const NX_35 = 1
const NY_35 = 2
const nG_35 = 2
const ng_35 = 2

function F_35(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]
end

function G_35(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-1;1]*x[1]-1
end

function f_35(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-y[1])^2+(y[2]+1)^2
end

function g_35(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [y[1]^3 .- y[2];-y[2]]
end

# Parsing instance LamparielloSagratella2017Ex31 (number 36)
const NX_36 = 1
const NY_36 = 1
const nG_36 = 1
const ng_36 = 1

function F_36(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]^2+y[1]^2
end

function G_36(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 1-x[1]
end

function f_36(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]
end

function g_36(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 1-x[1]-y[1]
end

# Parsing instance LamparielloSagratella2017Ex32 (number 37)
const NX_37 = 1
const NY_37 = 1
const nG_37 = 0
const ng_37 = 0

function F_37(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]^2+y[1]^2
end

function G_37(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_37(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]+y[1]-1)^2
end

function g_37(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

# Parsing instance LamparielloSagratella2017Ex33 (number 38)
const NX_38 = 1
const NY_38 = 2
const nG_38 = 1
const ng_38 = 3

function F_38(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]^2+(sum(y))^2
end

function G_38(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return .5-x[1]
end

function f_38(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]
end

function g_38(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [1-x[1]-sum(y);-y]
end

# Parsing instance LamparielloSagratella2017Ex35 (number 39)
const NX_39 = 1
const NY_39 = 1
const nG_39 = 2
const ng_39 = 3

function F_39(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]^2+y[1]^2
end

function G_39(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-1-x[1]; x[1]-1]
end

function f_39(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -y[1]
end

function g_39(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [2*x[1]+y[1]-2;-y[1];y[1]-1]
end

# Parsing instance LuDebSinha2016a (number 40)
const NX_40 = 1
const NY_40 = 1
const nG_40 = 4
const ng_40 = 0

function F_40(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    a = (0.2*y[1]-x[1]+0.6)/0.055
    return 2-exp(-a^0.4 )-0.8*exp(-( (0.15*y[1]+x[1]-0.4)/0.3 )^2 )
end

function G_40(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]; x[1]-1; -y[1]; y[1]-2]
end

function f_40(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    a = (1.5*y[1]-x[1])/0.055
    return 2-exp(-a^0.4)-0.8*exp(-( (2*y[1]+x[1]-3)/0.5 )^2 )
end

function g_40(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

# Parsing instance LuDebSinha2016b (number 41)
const NX_41 = 1
const NY_41 = 1
const nG_41 = 4
const ng_41 = 0

function F_41(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-0.5)^2+(y[1]-1)^2
end

function G_41(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]; x[1]-1; -y[1]; y[1]-2]
end

function f_41(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    a = (1.5*y[1]-x[1])/0.055
    return 2-exp(-a^0.4 )-0.8*exp(-( (2*y[1]+x[1]-3)/0.5 )^2 )
end

function g_41(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

# Parsing instance LuDebSinha2016c (number 42)
const NX_42 = 1
const NY_42 = 1
const nG_42 = 4
const ng_42 = 0

function F_42(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    a = (0.2*y[1]-x[1]+0.6)/0.055
    return 2-exp(-a^0.4 )-0.8*exp(-( (0.15*y[1]+x[1]-0.4)/0.3 )^2 )
end

function G_42(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]; x[1]-1; -y[1]; y[1]-2]
end

function f_42(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-0.5)^2+(y[1]-1)^2
end

function g_42(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

# Parsing instance LuDebSinha2016d (number 43)
const NX_43 = 2
const NY_43 = 2
const nG_43 = 11
const ng_43 = 3

function F_43(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[2]
end

function G_43(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    y1= y[1]/14+16/7
    return [-[4;100]-x; x-[10;200]; -[4;100]-y; y-[10;200]
    -y1*(x[1]-2)^2 .+ x[2]; 12.5*y1*(x[1]-5)-x[2]
    -5*(x[1]+4-y1)*(x[1]+8-y1)+x[2]]
end

function f_43(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -y[2]
end

function g_43(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    x1= x[1]/14+16/7
    return [-x1*(y[1]-2)^2 .+ y[2]; 12.5*x1*(y[1]-5)-y[2]
    -5*(y[1]+4-x1)*(y[1]+8-x1)+y[2]]
end

# Parsing instance LuDebSinha2016e (number 44)
const NX_44 = 1
const NY_44 = 2
const nG_44 = 6
const ng_44 = 3

function F_44(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-2.5)^2/0.04+(y[2]-50)^2/900
end

function G_44(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [2-x[1]; x[1]-3; -[4;100]-y; y-[10;200]]
end

function f_44(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -y[2]
end

function g_44(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]*(y[1]-2)^2 .+ y[2]; 12.5*x[1]*(y[1]-5)-y[2]
    -5*(y[1]+4-x[1])*(y[1]+8-x[1])+y[2]]
end

# Parsing instance LuDebSinha2016f (number 45)
const NX_45 = 2
const NY_45 = 1
const nG_45 = 9
const ng_45 = 0

function F_45(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[2]
end

function G_45(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    x1= x[1]/20
    return [2-y[1]; y[1]-4; -[80;100]-x; x-[200;200]
    -y[1]*(x1-2)^2 .+ x[2]; 12.5*y[1]*(x1-5)-x[2]
    -5*(x1+4-y[1])*(x1+8-y[1])+x[2] ]
end

function f_45(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-50)^2/784+(y[1]-2.5)^2/0.04
end

function g_45(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

# Parsing instance LucchettiEtal1987 (number 46)
const NX_46 = 1
const NY_46 = 1
const nG_46 = 2
const ng_46 = 2

function F_46(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (1-x[1])/2+x[1]*y[1]
end

function G_46(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]; x[1]-1]
end

function f_46(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-1)*y[1]
end

function g_46(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1];y[1]-1]
end

# Parsing instance MacalHurter1997 (number 47)
const NX_47 = 1
const NY_47 = 1
const nG_47 = 0
const ng_47 = 0

function F_47(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-1)^2+(y[1]-1)^2
end

function G_47(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_47(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*y[1]^2+500*y[1]-50*x[1]*y[1]
end

function g_47(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

# Parsing instance Mirrlees1999 (number 48)
const NX_48 = 1
const NY_48 = 1
const nG_48 = 0
const ng_48 = 2

function F_48(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-2)^2+(y[1]-1)^2
end

function G_48(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_48(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]*exp(-(y[1]+1)^2)-exp(-(y[1]-1)^2)
end

function g_48(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [y[1]-2; -y[1]-2]
end

# Parsing instance MitsosBarton2006Ex310 (number 49)
const NX_49 = 1
const NY_49 = 1
const nG_49 = 2
const ng_49 = 2

function F_49(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]
end

function G_49(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]+0.1; x[1]-1]
end

function f_49(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]*(16*y[1]^4+2*y[1]^3-8*y[1]^2-1.5*y[1]+0.5)
end

function g_49(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance MitsosBarton2006Ex311 (number 50)
const NX_50 = 1
const NY_50 = 1
const nG_50 = 2
const ng_50 = 2

function F_50(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]
end

function G_50(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1]
end

function f_50(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]*(16*y[1]^4+2*y[1]^3-8*y[1]^2-1.5*y[1]+0.5)
end

function g_50(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-0.8; y[1]-1]
end

# Parsing instance MitsosBarton2006Ex312 (number 51)
const NX_51 = 1
const NY_51 = 1
const nG_51 = 2
const ng_51 = 2

function F_51(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]+x[1]*y[1]+10*y[1]^2
end

function G_51(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1]
end

function f_51(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]*y[1]^2+0.5*y[1]^4
end

function g_51(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance MitsosBarton2006Ex313 (number 52)
const NX_52 = 1
const NY_52 = 1
const nG_52 = 2
const ng_52 = 2

function F_52(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]-y[1]
end

function G_52(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1]
end

function f_52(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]*y[1]*(y[1]/2-x[1]^2)
end

function g_52(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance MitsosBarton2006Ex314 (number 53)
const NX_53 = 1
const NY_53 = 1
const nG_53 = 2
const ng_53 = 2

function F_53(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-0.25)^2+y[1]^2
end

function G_53(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1]
end

function f_53(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]^3/3-x[1]*y[1]
end

function g_53(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance MitsosBarton2006Ex315 (number 54)
const NX_54 = 1
const NY_54 = 1
const nG_54 = 2
const ng_54 = 2

function F_54(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]+y[1]
end

function G_54(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1]
end

function f_54(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]*y[1]^2/2-y[1]^3/3
end

function g_54(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance MitsosBarton2006Ex316 (number 55)
const NX_55 = 1
const NY_55 = 1
const nG_55 = 2
const ng_55 = 2

function F_55(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 2*x[1]+y[1]
end

function G_55(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1]
end

function f_55(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]*y[1]^2/2-y[1]^4/4
end

function g_55(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance MitsosBarton2006Ex317 (number 56)
const NX_56 = 1
const NY_56 = 1
const nG_56 = 2
const ng_56 = 2

function F_56(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]+0.5)^2+y[1]^2/2
end

function G_56(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1]
end

function f_56(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]*y[1]^2/2+y[1]^4/4
end

function g_56(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance MitsosBarton2006Ex318 (number 57)
const NX_57 = 1
const NY_57 = 1
const nG_57 = 2
const ng_57 = 2

function F_57(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]^2+y[1]^2
end

function G_57(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1]
end

function f_57(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]*y[1]^2-y[1]^4/2
end

function g_57(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance MitsosBarton2006Ex319 (number 58)
const NX_58 = 1
const NY_58 = 1
const nG_58 = 2
const ng_58 = 2

function F_58(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-1+y[1]/2)*y[1]
end

function G_58(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1]
end

function f_58(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (-x[1]+y[1]^2/2)*y[1]^2
end

function g_58(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance MitsosBarton2006Ex320 (number 59)
const NX_59 = 1
const NY_59 = 1
const nG_59 = 2
const ng_59 = 2

function F_59(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-0.25)^2+y[1]^2
end

function G_59(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1]
end

function f_59(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]^3/3-x[1]^2*y[1]
end

function g_59(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance MitsosBarton2006Ex321 (number 60)
const NX_60 = 1
const NY_60 = 1
const nG_60 = 2
const ng_60 = 2

function F_60(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]+0.6)^2+y[1]^2
end

function G_60(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1]
end

function f_60(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]^4+(4/30)*(1-x[1])*y[1]^3+(-0.02*x[1]^2+0.16*x[1]-0.4)*y[1]^2+(0.004*x[1]^3-0.036*x[1]^2+0.08*x[1])*y[1]
end

function g_60(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance MitsosBarton2006Ex322 (number 61)
const NX_61 = 1
const NY_61 = 1
const nG_61 = 2
const ng_61 = 3

function F_61(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]+0.6)^2+y[1]^2
end

function G_61(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1]
end

function f_61(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]^4+(4/30)*(1-x[1])*y[1]^3+(-0.02*x[1]^2+0.16*x[1]-0.4)*y[1]^2+(0.004*x[1]^3-0.036*x[1]^2+0.08*x[1])*y[1]
end

function g_61(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1; 0.01*(1+x[1]^2)-y[1]^2]
end

# Parsing instance MitsosBarton2006Ex323 (number 62)
const NX_62 = 1
const NY_62 = 1
const nG_62 = 3
const ng_62 = 3

function F_62(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]^2
end

function G_62(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1; 1+x[1]-9*x[1]^2-y[1]]
end

function f_62(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]
end

function g_62(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1; y[1]^2*(x[1]-0.5)]
end

# Parsing instance MitsosBarton2006Ex324 (number 63)
const NX_63 = 1
const NY_63 = 1
const nG_63 = 2
const ng_63 = 2

function F_63(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]^2-y[1]
end

function G_63(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]; x[1]-1]
end

function f_63(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return ((y[1]-1-0.1*x[1])^2-0.5-0.5*x[1])^2
end

function g_63(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]; y[1]-3]
end

# Parsing instance MitsosBarton2006Ex38 (number 64)
const NX_64 = 1
const NY_64 = 1
const nG_64 = 4
const ng_64 = 2

function F_64(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]^2
end

function G_64(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1; -y[1]-0.1; y[1]-0.1]
end

function f_64(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]*y[1]+exp(x[1])*y[1]
end

function g_64(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [ -y[1]-1; y[1]-1]
end

# Parsing instance MitsosBarton2006Ex39 (number 65)
const NX_65 = 1
const NY_65 = 1
const nG_65 = 3
const ng_65 = 2

function F_65(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]
end

function G_65(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-1 1;-1 0; 1 0]*[x[1];y[1]]-[0; 10; 10]
end

function f_65(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]^3
end

function g_65(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance MorganPatrone2006a (number 66)
const NX_66 = 1
const NY_66 = 1
const nG_66 = 2
const ng_66 = 2

function F_66(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -(x[1]+y[1])
end

function G_66(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-0.5;x[1]-0.5]
end

function f_66(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]*y[1]
end

function g_66(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance MuuQuy2003Ex1 (number 67)
const NX_67 = 1
const NY_67 = 2
const nG_67 = 2
const ng_67 = 3

function F_67(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]^2-4*x[1]+y'*y
end

function G_67(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1];x[1]-2]
end

function f_67(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]^2 .+ y[2]^2/2 .+ y[1]*y[2]+[1-3*x[1] 1+x[1]]*y
end

function g_67(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [[2 1]*y .- 2*x[1]-1; -y]
end

# Parsing instance NieWangYe2017Ex34 (number 68)
const NX_68 = 1
const NY_68 = 2
const nG_68 = 2
const ng_68 = 2

function F_68(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]+sum(y)
end

function G_68(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]+2; x[1]-3]
end

function f_68(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]*sum(y)
end

function g_68(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]^2 .+ y[2]^2+(y[1]^2 .+ y[2]^2)^2; -y[1]]
end

# Parsing instance NieWangYe2017Ex61 (number 69)
const NX_69 = 2
const NY_69 = 2
const nG_69 = 5
const ng_69 = 1

function F_69(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]^3*(x[1]^2-3*x[1]*x[2])-y[1]^2*y[2]+y[2]*x[2]^3
end

function G_69(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x .- 1; -x .- 1;-y[2]-y[1]*(1 .- x[1]^2)]
end

function f_69(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]*y[2]^2 .- y[2]^3 .- y[1]^2*(x[2]-x[1]^2)
end

function g_69(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y'*y .- 1
end

# Parsing instance Outrata1990Ex1a (number 70)
const NX_70 = 2
const NY_70 = 2
const nG_70 = 0
const ng_70 = 4

function F_70(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.1*(x'*x)+0.5*sum((y-[3; 4]).^2)-12.5
end

function G_70(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_70(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*(y'*[1 -2; -2 5]*y)-x'*y
end

function g_70(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [[-0.333 1]*y .- 2; [1 -0.333]*y .- 2; -y]
end

# Parsing instance Outrata1990Ex1b (number 71)
const NX_71 = 2
const NY_71 = 2
const nG_71 = 0
const ng_71 = 4

function F_71(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x'*x .+ 0.5*sum((y-[3; 4]).^2)-12.5
end

function G_71(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_71(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*(y'*[1 -2; -2 5]*y)-x'*y
end

function g_71(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [[-0.333 1]*y .- 2; [1 -0.333]*y .- 2; -y]
end

# Parsing instance Outrata1990Ex1c (number 72)
const NX_72 = 2
const NY_72 = 2
const nG_72 = 0
const ng_72 = 4

function F_72(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*sum((y-[3; 4]).^2)-12.5
end

function G_72(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_72(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*(y'*[1 3; 3 10]*y)-x'*y
end

function g_72(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [[-0.333 1]*y .- 2; [1 -0.333]*y .- 2; -y]
end

# Parsing instance Outrata1990Ex1d (number 73)
const NX_73 = 2
const NY_73 = 2
const nG_73 = 0
const ng_73 = 4

function F_73(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.1*(x'*x)+0.5*sum((y-[3; 4]).^2)-12.5
end

function G_73(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_73(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*(y'*[1 3; 3 10]*y)-x'*y
end

function g_73(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [[-0.333 1]*y .- 2; [1 -0.333]*y .- 2; -y]
end

# Parsing instance Outrata1990Ex1e (number 74)
const NX_74 = 2
const NY_74 = 2
const nG_74 = 0
const ng_74 = 4

function F_74(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.1*(x'*x)+0.5*sum((y-[3; 4]).^2)-12.5
end

function G_74(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_74(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*(y'*[1 3; 3 10]*y)-y'*[-1 2; 3 -3]*x
end

function g_74(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [[-0.333 1]*y .- 2; [1 -0.333]*y .- 2; -y]
end

# Parsing instance Outrata1990Ex2a (number 75)
const NX_75 = 1
const NY_75 = 2
const nG_75 = 1
const ng_75 = 4

function F_75(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*sum((y-[3; 4]).^2)
end

function G_75(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]
end

function f_75(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*(y'*y)-[3+1.333*x[1] x[1]] *y
end

function g_75(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [[-0.333 1]*y .- 2; [1 -0.333]*y .- 2; -y]
end

# Parsing instance Outrata1990Ex2b (number 76)
const NX_76 = 1
const NY_76 = 2
const nG_76 = 1
const ng_76 = 4

function F_76(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*sum((y-[3; 4]).^2)
end

function G_76(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]
end

function f_76(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*(y'*[1+x[1] 0;0 0]*y)-[3+1.333*x[1] x[1]] *y
end

function g_76(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [[-0.333 1]*y .- 2; [1 -0.333]*y .- 2; -y]
end

# Parsing instance Outrata1990Ex2c (number 77)
const NX_77 = 1
const NY_77 = 2
const nG_77 = 1
const ng_77 = 4

function F_77(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*sum((y-[3; 4]).^2)
end

function G_77(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]
end

function f_77(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*(y'*[1+x[1] 0;0 1+0.1*x[1]]*y)-[3+1.333*x[1] x[1]] *y
end

function g_77(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [[-0.333 1]*y .- 2; [1 -0.333]*y .- 2; -y]
end

# Parsing instance Outrata1990Ex2d (number 78)
const NX_78 = 1
const NY_78 = 2
const nG_78 = 1
const ng_78 = 4

function F_78(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*sum((y-[3; 4]).^2)
end

function G_78(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]
end

function f_78(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*(y'*y)-[3+1.333*x[1] x[1]] *y
end

function g_78(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [[-0.333+0.1*x[1] 1]*y-x[1]; [1 -0.333-0.1*x[1]]*y .- 2; -y]
end

# Parsing instance Outrata1990Ex2e (number 79)
const NX_79 = 1
const NY_79 = 2
const nG_79 = 1
const ng_79 = 4

function F_79(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*sum((y-[3; 4]).^2)
end

function G_79(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]
end

function f_79(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*(y'*[1+x[1] 0;0 1]*y)-[3+1.333*x[1] x[1]] *y
end

function g_79(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [[-0.333+0.1*x[1] 1]*y-x[1]; [1 -0.333-0.1*x[1]]*y .- 2; -y]
end

# Parsing instance Outrata1993Ex31 (number 80)
const NX_80 = 1
const NY_80 = 2
const nG_80 = 1
const ng_80 = 4

function F_80(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*sum((y-[3; 4]).^2)
end

function G_80(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]
end

function f_80(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*(1+0.2*x[1])*y[1]^2+0.5*(1+0.1*x[1])*y[2]^2-[3+1.333*x[1] x[1]]*y
end

function g_80(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [[-0.333+0.1*x[1] 1]*y .+ 0.1*x[1]-2; [ 1 -0.333-0.1*x[1]]*y .+ 0.1*x[1]-2; -y]
end

# Parsing instance Outrata1993Ex32 (number 81)
const NX_81 = 1
const NY_81 = 2
const nG_81 = 1
const ng_81 = 4

function F_81(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*sum((y-[3;4]).^2)
end

function G_81(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]
end

function f_81(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*(1+0.2*x[1])*y[1]^2+0.5*(1+0.1*x[1])*y[2]^2-(3+1.333*x[1])*y[1]-x[1]*y[2]
end

function g_81(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [[-0.333 1]*y .+ 0.1*x[1]-1; y'*y .- 0.1*x[1]-9; -y]
end

# Parsing instance Outrata1994Ex31 (number 82)
const NX_82 = 1
const NY_82 = 2
const nG_82 = 2
const ng_82 = 4

function F_82(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*sum((y-[3;4]).^2)
end

function G_82(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x[1]-10;-x[1]]
end

function f_82(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*(1+0.2*x[1])*y[1]^2+0.5*(1+0.1*x[1])*y[2]^2-(3+1.333*x[1])*y[1]-x[1]*y[2]
end

function g_82(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [[-0.333 1]*y .+ 0.1*x[1]-1; y'*y .- 0.1*x[1]-9; -y]
end

# Parsing instance OutrataCervinka2009 (number 83)
const NX_83 = 2
const NY_83 = 2
const nG_83 = 1
const ng_83 = 3

function F_83(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -[2 0.5]*x-[0 1]*y
end

function G_83(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [1 0]*x
end

function f_83(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [1 -1]*y+x'*y+y'*y/2
end

function g_83(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [0 1; -1 1; 1 1]*y
end

# Parsing instance PaulaviciusAdjiman2017a (number 84)
const NX_84 = 1
const NY_84 = 1
const nG_84 = 4
const ng_84 = 2

function F_84(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]^2+y[1]^2
end

function G_84(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1; -y[1]-1; y[1]-1]
end

function f_84(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]*y[1]^2-y[1]^4/2
end

function g_84(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance PaulaviciusAdjiman2017b (number 85)
const NX_85 = 1
const NY_85 = 1
const nG_85 = 4
const ng_85 = 2

function F_85(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]+y[1]
end

function G_85(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]-1; x[1]-1; -y[1]-1; y[1]-1]
end

function f_85(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return .5*x[1]*y[1]^2-(x[1]^3)*y[1]
end

function g_85(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]-1; y[1]-1]
end

# Parsing instance SahinCiric1998Ex2 (number 86)
const NX_86 = 1
const NY_86 = 1
const nG_86 = 2
const ng_86 = 3

function F_86(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-3)^2+(y[1]-2)^2
end

function G_86(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]; x[1]-8]
end

function f_86(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (y[1]-5)^2
end

function g_86(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-2*x[1]+y[1]-1; x[1]-2*y[1]+2; x[1]+2*y[1]-14]
end

# Parsing instance ShimizuAiyoshi1981Ex1 (number 87)
const NX_87 = 1
const NY_87 = 1
const nG_87 = 3
const ng_87 = 3

function F_87(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]^2+(y[1]-10)^2
end

function G_87(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x[1]-15; -x[1]+y[1]; -x[1]]
end

function f_87(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]+2*y[1]-30)^2
end

function g_87(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [x[1]+y[1]-20; y[1]-20; -y[1]]
end

# Parsing instance ShimizuAiyoshi1981Ex2 (number 88)
const NX_88 = 2
const NY_88 = 2
const nG_88 = 3
const ng_88 = 4

function F_88(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return sum((x-[30;20]).^2)+[-20 20]*y
end

function G_88(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-[1 2]*x .+ 30; [1 1]*x .- 25; [0 1]*x .- 15]
end

function f_88(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return sum((x-y).^2)
end

function g_88(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [ y .- 10; -y]
end

# Parsing instance ShimizuEtal1997a (number 89)
const NX_89 = 1
const NY_89 = 1
const nG_89 = 0
const ng_89 = 3

function F_89(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-5)^2+(2*y[1]+1)^2
end

function G_89(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [ ]
end

function f_89(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (y[1]-1)^2-1.5*x[1]*y[1]
end

function g_89(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-3*x[1]+y[1]+3; x[1]-0.5*y[1]-4; x[1]+y[1]-7]
end

# Parsing instance ShimizuEtal1997b (number 90)
const NX_90 = 1
const NY_90 = 1
const nG_90 = 2
const ng_90 = 2

function F_90(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 16*x[1]^2+9*y[1]^2
end

function G_90(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1];   -4*x[1]+y[1]]
end

function f_90(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]+y[1]-20)^4
end

function g_90(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1];   4*x[1]+y[1]-50]
end

# Parsing instance SinhaMaloDeb2014TP3 (number 91)
const NX_91 = 2
const NY_91 = 2
const nG_91 = 3
const ng_91 = 4

function F_91(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x'*diag([-1 -3])*x .- 4*y[1]+y[2]^2
end

function G_91(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x; x[1]^2+2*x[2]-4]
end

function f_91(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 2*x[1]^2 .+ y[1]^2-5*y[2]
end

function g_91(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y; [0 -1]*x+[-3 4]*y .+ 4; -x[1]^2+2*x[1]-x[2]^2+[2 -1]*y .- 3]
end

# Parsing instance SinhaMaloDeb2014TP6 (number 92)
const NX_92 = 1
const NY_92 = 2
const nG_92 = 1
const ng_92 = 6

function F_92(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-1)^2-2*x[1]+2*y[1]
end

function G_92(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -x[1]
end

function f_92(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return sum((2*y-[4;1]).^2)+x[1]*y[1]
end

function g_92(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y;4*x[1]+[5 4]*y .- 12;-4*x[1]+[-5 4]*y .+ 4; 4*x[1]+[-4 5]*y .- 4;-4*x[1]+[4 5]*y .- 4]
end

# Parsing instance SinhaMaloDeb2014TP7 (number 93)
const NX_93 = 2
const NY_93 = 2
const nG_93 = 4
const ng_93 = 4

function F_93(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -(x[1]+y[1])*(x[2]+y[2])/(1+sum(x.*y))
end

function G_93(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x; [1 -1]*x; sum(x.*x)-100]
end

function f_93(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]+y[1])*(x[2]+y[2])/(1+sum(x.*y))
end

function g_93(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y;y-x]
end

# Parsing instance SinhaMaloDeb2014TP8 (number 94)
const NX_94 = 2
const NY_94 = 2
const nG_94 = 5
const ng_94 = 6

function F_94(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return ([2 2]*x+[-3 -3]*y .- 60)^2
end

function G_94(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [ -x; x .- 50; [1 1]*x+[1 -2]*y .- 40]
end

function f_94(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return sum((y-x .+ 20).^2)
end

function g_94(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [2*y-x .+ 10; y .- 20; -y .- 10]
end

# Parsing instance TuyEtal2007 (number 95)
const NX_95 = 1
const NY_95 = 1
const nG_95 = 2
const ng_95 = 3

function F_95(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]^2+y[1]^2
end

function G_95(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]; -y[1]]
end

function f_95(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -y[1]
end

function g_95(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [3 1; 1 1; 1 3]*[x[1];y[1]]-[15; 7; 15]
end

# Parsing instance Vogel2012 (number 96)
const NX_96 = 1
const NY_96 = 1
const nG_96 = 2
const ng_96 = 1

function F_96(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (y[1]+1)^2
end

function G_96(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-3-x[1]; x[1]-2]
end

function f_96(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]^3-3*y[1]
end

function g_96(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]-y[1]
end

# Parsing instance YeZhu2010Ex42 (number 97)
const NX_97 = 1
const NY_97 = 1
const nG_97 = 2
const ng_97 = 1

function F_97(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-1)^2+y[1]^2
end

function G_97(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-3-x[1]; x[1]-2]
end

function f_97(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]^3-3*y[1]
end

function g_97(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]-y[1]
end

# Parsing instance YeZhu2010Ex43 (number 98)
const NX_98 = 1
const NY_98 = 1
const nG_98 = 2
const ng_98 = 1

function F_98(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return (x[1]-1/2)^2+(y[1]-2)^2
end

function G_98(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]; x[1]-4]
end

function f_98(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return y[1]^3-3*y[1]
end

function g_98(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]-y[1]-3
end

# Parsing instance Yezza1996Ex31 (number 99)
const NX_99 = 1
const NY_99 = 1
const nG_99 = 2
const ng_99 = 2

function F_99(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -(4*x[1]-3)*y[1]+2*x[1]+1
end

function G_99(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1]; x[1]-1]
end

function f_99(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -(1-4*x[1])*y[1]-2*x[1]-2
end

function g_99(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]; y[1]-1]
end

# Parsing instance Yezza1996Ex41 (number 100)
const NX_100 = 1
const NY_100 = 1
const nG_100 = 0
const ng_100 = 2

function F_100(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*(y[1]-2)^2+0.5*(x[1]-y[1]-2)^2
end

function G_100(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_100(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return 0.5*y[1]^2 +x[1]-y[1]
end

function g_100(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-y[1]; y[1]-x[1]]
end

# Parsing instance Zlobec2001a (number 101)
const NX_101 = 1
const NY_101 = 2
const nG_101 = 0
const ng_101 = 3

function F_101(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -y[1]/x[1]
end

function G_101(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return []
end

function f_101(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-1 -1]*y
end

function g_101(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-1 .+ y[1]+x[1]*y[2]; -y]
end

# Parsing instance Zlobec2001b (number 102)
const NX_102 = 1
const NY_102 = 1
const nG_102 = 2
const ng_102 = 4

function F_102(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return x[1]+y[1]
end

function G_102(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [-x[1];x[1]-1]
end

function f_102(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return -y[1]
end

function g_102(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    return [ -y[1]; y[1]-1; -x[1]*y[1]; x[1]*y[1]]
end

# Testbed of BOLIBver2
const testbed = [
    "AiyoshiShimizu1984Ex2",
    "AllendeStill2013",
    "Bard1988Ex1",
    "Bard1988Ex3",
    "Bard1991Ex1",
    "BardBook1998",
    "CalamaiVicente1994a",
    "ClarkWesterberg1990a",
    "Colson2002BIPA1",
    "Colson2002BIPA2",
    "Colson2002BIPA3",
    "Colson2002BIPA4",
    "Colson2002BIPA5",
    "DeSilva1978",
    "Dempe1992a",
    "Dempe1992b",
    "DempeDutta2012Ex24",
    "DempeDutta2012Ex31",
    "DempeEtal2012",
    "DempeFranke2011Ex41",
    "DempeFranke2011Ex42",
    "DempeFranke2014Ex38",
    "DempeLohse2011Ex31a",
    "FalkLiu1995",
    "FloudasEtal2013",
    "FloudasZlobec1998",
    "GumusFloudas2001Ex1",
    "GumusFloudas2001Ex4",
    "GumusFloudas2001Ex5",
    "HatzEtal2013",
    "HendersonQuandt1958",
    "HenrionSurowiec2011",
    "IshizukaAiyoshi1992a",
    "KleniatiAdjiman2014Ex3",
    "LamparielloSagratella2017Ex23",
    "LamparielloSagratella2017Ex31",
    "LamparielloSagratella2017Ex32",
    "LamparielloSagratella2017Ex33",
    "LamparielloSagratella2017Ex35",
    "LuDebSinha2016a",
    "LuDebSinha2016b",
    "LuDebSinha2016c",
    "LuDebSinha2016d",
    "LuDebSinha2016e",
    "LuDebSinha2016f",
    "LucchettiEtal1987",
    "MacalHurter1997",
    "Mirrlees1999",
    "MitsosBarton2006Ex310",
    "MitsosBarton2006Ex311",
    "MitsosBarton2006Ex312",
    "MitsosBarton2006Ex313",
    "MitsosBarton2006Ex314",
    "MitsosBarton2006Ex315",
    "MitsosBarton2006Ex316",
    "MitsosBarton2006Ex317",
    "MitsosBarton2006Ex318",
    "MitsosBarton2006Ex319",
    "MitsosBarton2006Ex320",
    "MitsosBarton2006Ex321",
    "MitsosBarton2006Ex322",
    "MitsosBarton2006Ex323",
    "MitsosBarton2006Ex324",
    "MitsosBarton2006Ex38",
    "MitsosBarton2006Ex39",
    "MorganPatrone2006a",
    "MuuQuy2003Ex1",
    "NieWangYe2017Ex34",
    "NieWangYe2017Ex61",
    "Outrata1990Ex1a",
    "Outrata1990Ex1b",
    "Outrata1990Ex1c",
    "Outrata1990Ex1d",
    "Outrata1990Ex1e",
    "Outrata1990Ex2a",
    "Outrata1990Ex2b",
    "Outrata1990Ex2c",
    "Outrata1990Ex2d",
    "Outrata1990Ex2e",
    "Outrata1993Ex31",
    "Outrata1993Ex32",
    "Outrata1994Ex31",
    "OutrataCervinka2009",
    "PaulaviciusAdjiman2017a",
    "PaulaviciusAdjiman2017b",
    "SahinCiric1998Ex2",
    "ShimizuAiyoshi1981Ex1",
    "ShimizuAiyoshi1981Ex2",
    "ShimizuEtal1997a",
    "ShimizuEtal1997b",
    "SinhaMaloDeb2014TP3",
    "SinhaMaloDeb2014TP6",
    "SinhaMaloDeb2014TP7",
    "SinhaMaloDeb2014TP8",
    "TuyEtal2007",
    "Vogel2012",
    "YeZhu2010Ex42",
    "YeZhu2010Ex43",
    "Yezza1996Ex31",
    "Yezza1996Ex41",
    "Zlobec2001a",
    "Zlobec2001b",
]
